### PR TITLE
Create hypernative

### PR DESCRIPTION
**Pull request by adizep**
Add Hypernative company description to security tools

### CODE REVIEW

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Hihi! Can you add Hypernative to the `project-words.txt`: https://github.com/Consensys/doc.zk-evm/actions/runs/7566774790/job/20659901803?pr=398

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Can you add Hypernative to `project-words.txt` to pass linting
https://github.com/Consensys/doc.zk-evm/actions/runs/7744638145/job/21118822498?pr=398

Also, you'll need to add hypernative to `sidebars.js` in order for this to show up

**Comment by jlwllmr** [comment]
@adizep bump — could you address the comments above please?

**Comment by jlwllmr** [comment]
@adizep bump — could you address these few edits please? thanks!

**Review by jlwllmr — APPROVED** [review]

**Pull request merged**
