### PR TITLE
Linea brand refresh

### PR DESCRIPTION
**Pull request by sammysango**
Overhaul of the site's frontend to bring it up to speed with Linea's recent refresh of the brand.
linea_brand_refresh

### CODE REVIEW

**Comment by jlwllmr** [comment]
This is beautiful! Just a few things to potentially touch up, if possible: 

The padding/spacing around the social links and the search bar seems a bit uneven:
image

The release notes tooltip/popup also doesn't seem vertically aligned:
image

When a section is selected, the highlighting has a kind of padding on the left side (closer to the edge of the screen), but on the right it extends all the way to the edge of the container: 
image

The release notes icon disappears when you narrow the viewport:
image

The "on this page" is barely readable on dark mode in narrow viewports:
image

**Comment by sammysango** [comment]
@jlwllmr Good catches!

Those first two are related - Chrome at regular 100% zoom seems okay for me, but there's some minor adjustment needed for other browsers, possibly. I can't tell from the screenshot -- is this vertical misalignment a result of one or more of the left navbar items (users, developers, architecture etc) splitting into two lines at certain viewport widths, and causing unwanted height changes to the navbar? Or are you seeing it at all screen widths regardless?

The rest is easily fixed. The release notes icon disappearing a little bit before mobile/side menu collapse was an intentional workaround to fitting everything into the navbar, by removing it for a small number of uncommon viewport sizes, but I'll see if I can a) bring it back while still fitting everything in, or b) maybe we just collapse into a mobile view 100px or so earlier, so we're not so stuck for space.

**Comment by jlwllmr** [comment]
@sammysango On the vertical alignment, you're right — when I added the above comment I was viewing on my laptop monitor rather than external. Now, on the external monitor, it's fine at 100%:
image

But starts to deteriorate at 175%: 
image

The left-hand navbar elements wrap over two lines only at the _very last moment_ before the navbar adjusts for a narrow viewport. Otherwise, they stay on one line:
image

But in any case, it seems unrelated to the vertical alignment of the search bar and other elements.

> release notes icon disappearing a little bit before mobile/side menu collapse was an intentional workaround to fitting everything into the navbar 
Yeah, I thought that might be the case, and it definitely makes sense. It's just that once it's disappeared, there's a brief range of viewport widths where there's nowhere to access it, because the hamburger icon hasn't yet appeared. A minor point but could be problematic depending on screen size. (Though the search bar should still allow you to find it if you need it.) Like you say, those viewport dimensions are pretty unusual, but they may arise if people split their screen vertically, which isn't that uncommon (?). Or maybe tablets held vertically. 

Also noticed that narrower screens cause some issues for the developer quickstart card:
image

**Comment by sammysango** [comment]
@jlwllmr All noted, and will tackle these over today/tomorrow. For the release notes issue, I might delve into the navbar component to make the hamburger menu collapse occur sooner, by 200px or so; and that homepage card overlap with the title/icon is probably most easily solved by just hiding the icons for very narrow displays.

Will follow up once changes are made for this and the rest of the above, so you can review!

**Review by jlwllmr — APPROVED** [review]
gorgeous!

**Pull request merged**
