### PR TITLE
Adding EasyNode to the projects list

### PR DESCRIPTION
**Pull request by maximegris**
Adding EasyNode to the projects list 
And keep the original order of the Node providers list.
None is more legitimate than the other so the initial order should not be altered here.

### CODE REVIEW

**Comment by jlwllmr** [comment]
@maximegris could you please `merge main` and then address any conflicts? We restructured the docs recently, so the paths may be different. Thanks!

**Comment by maximegris** [comment]
Sure, thank you @jlwllmr

**Comment by maximegris** [comment]
Indeed the path has changed.
The PR is now up-to-date with the `main` branch. @jlwllmr

**Review by jlwllmr — APPROVED** [review]

**Comment by jlwllmr** [comment]
@maximegris thanks for adjusting! seeing as EasyNode is already in the list on `main`, and this PR intends to revert to an initial ordering, I've pushed a commit that just sets the list in alphabetical order to preclude any bias. I'll merge — thanks for your help with this.

**Pull request merged**
